def print_rules(bit):
    rule_XOR = (
        "// REG ^= (1 << %d)" % bit,
        "replace restart {",
        "    ld a, %1",
        "    xor a, #%s" % format(1 << bit, '#04x'),
        "    ldw %2, #%1",
        "    ld (%2), a",
        "} by {",
        "    bcpl %%1, #%d ; peephole replaced xor by bcpl." % bit,
        "} if notUsed('a')")

    rule_AND = (
        "// REG |= (1 << %d)" % bit,
        "replace restart {",
        "    ld  a, %1",
        "    or  a, #%s" % format((1 << bit) & 0xff, '#04x'),
        "    ldw %2, #%1",
        "    ld  (%2), a",
        "} by {",
        "    bset %%1, #%d ; peephole replaced or by bcpl." % bit,
        "} if notUsed('a')")

    rule_OR = (
        "// REG &= ~(1 << %d)" % bit,
        "replace restart {",
        "    ld  a, %1",
        "    and a, #%s" % format(~(1 << bit) & 0xff, '#04x'),
        "    ldw %2, #%1",
        "    ld  (%2), a",
        "} by {",
        "    bres %%1, #%d ; peephole replaced and by bcpl." % bit,
        "} if notUsed('a')")

    for r in (rule_AND, rule_OR, rule_XOR):
        print ('\n'.join(r) + '\n')

print('// Extra rules generated by rules_gen.py')
for i in range(8):
    print_rules(i)
